# Generated by Django 3.2.21 on 2023-10-08 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(blank=True, related_name='events_going', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='not_going',
            field=models.ManyToManyField(blank=True, related_name='events_not_going', to=settings.AUTH_USER_MODEL),
        ),
    ]
